[package]
name = "stacks-devnet-api"
version = "0.1.0"
edition = "2021"
authors = ["Micaiah Reid <micaiah@hiro.so>"]
description = "The Stacks Devnet API runs a server that can be used to deploy, delete, manage, and make requests to Stacks Devnets run on Kubernetes."
readme = "README.md"
exclude = ["examples/**", "scripts/**"]
homepage = "https://github.com/hirosystems/stacks-devnet-api"
repository = "https://github.com/hirosystems/stacks-devnet-api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version="0.82.2", features = ["client", "runtime"] }
k8s-openapi = { version = "0.18.0", features = ["v1_25"] }
futures = "0.3.28"
tokio = { version = "1.27.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.8.23"
hyper = { version = "0.14", features = ["full"] }
tower = "0.4.13"
http-body = "0.4.5"
hiro-system-kit = {version = "0.1.0", features = ["log"]}
strum_macros = "0.24.3"
strum = "0.24.1"
base64 = "0.21.2"
clarity-vm = "2.1.1"
clarity-repl = "1.6.4"
clarinet-files = "1.0.0"
chainhook-types = "1.0.1"
clarinet-deployments = "1.0.1"
toml = "0.5.9"

[dev-dependencies]
tower-test = "0.4.0"
test-case = "3.1.0"
