openapi: 3.0.3
info:
  title: Stacks Devnet API
  version: 0.0.1
tags:
  - name: Devnet Management
    description: Creation and management of a devnet
  - name: Devnet Request Proxy
    description: Request proxying to underlying nodes
paths:
  /api/v1/networks:
    post:
      tags:
        - Devnet Management
      summary: Create a new devnet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StacksDevnetConfig'
        required: true
      responses:
        '200':
          description: Successful creation of a devnet
        '400':
          description: Namespace does not exist
        '500':
          description: Internal server error
  /api/v1/network/{namespace}:
    get:
      tags:
        - Devnet Management
      summary: Get devnet status
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to query
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StacksDevnetInfoResponse'
        '500':
          description: Internal server error
    delete:
      tags:
        - Devnet Management
      summary: Deletes a devnet
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal server error
  /api/v1/network/{namespace}/bitcoin-node/*:
    get:
      tags:
        - Devnet Request Proxy
      summary: Forwards request headers, url parameters after "/bitcoin-node/", and request body to the Devnet's underlying bitcoin node.
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: the bitcoin node's reponse to the request
    post:
      tags:
        - Devnet Request Proxy
      summary: Forwards request headers, url parameters after "/bitcoin-node/", and request body to the Devnet's underlying bitcoin node.
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: the bitcoin node's reponse to the request
  /api/v1/network/{namespace}/stacks-node/*:
    get:
      tags:
        - Devnet Request Proxy
      summary: Forwards request headers, url parameters after "/stacks-node/", and request body to the Devnet's underlying stacks node.
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: the stacks node's reponse to the request
    post:
      tags:
        - Devnet Request Proxy
      summary: Forwards request headers, url parameters after "/stacks-node/", and request body to the Devnet's underlying stacks node.
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: the stacks node's reponse to the request
  /api/v1/network/{namespace}/stacks-api/*:
    get:
      tags:
        - Devnet Request Proxy
      summary: Forwards request headers, url parameters after "/stacks-api/", and request body to the Devnet's underlying stacks api.
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: the stacks api's reponse to the request
    post:
      tags:
        - Devnet Request Proxy
      summary: Forwards request headers, url parameters after "/stacks-api/", and request body to the Devnet's underlying stacks api.
      parameters:
        - name: namespace
          in: path
          description: namespace of the devnet to delete
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: the stacks api's reponse to the request
components:
  schemas:
    StacksDevnetInfoResponse:
      type: object
      properties:
        bitcoind_node_status: 
          type: string
        stacks_node_status: 
          type: string
        stacks_api_status: 
          type: string
        bitcoind_node_started_at: 
          type: string
        stacks_node_started_at: 
          type: string
        stacks_api_started_at: 
          type: string
        stacks_chain_tip: 
          type: integer
        bitcoin_chain_tip: 
          type: integer
    StacksDevnetConfig: 
      type: object
      required:
      - accounts
      - bitcoin_node_password
      - bitcoin_node_username
      - contracts
      - deployment_plan
      - disable_stacks_api
      - namespace
      - project_manifest
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountConfig'
        bitcoin_controller_automining_disabled:
          type: boolean
        bitcoin_controller_block_time:
            type: integer
            format: uint64
            minimum: 0.0
        bitcoin_node_password:
          type: string
        bitcoin_node_username:
          type: string
        contracts:
          type: array
          items:
            $ref: '#/components/schemas/ContractConfig'
        deployment_fee_rate:
            type: integer
            format: uint64
            minimum: 0.0
        deployment_plan:
          $ref: '#/components/schemas/DeploymentSpecificationFile'
        disable_bitcoin_explorer:
          type: boolean
        disable_stacks_api:
          type: boolean
        disable_stacks_explorer:
          type: boolean
        epoch_2_0:
          type: integer
          format: uint64
          minimum: 0.0
        epoch_2_05:
          type: integer
          format: uint64
          minimum: 0.0
        epoch_2_1:
          type: integer
          format: uint64
          minimum: 0.0
        epoch_2_2:
          type: integer
          format: uint64
          minimum: 0.0
        faucet_derivation_path:
          type: string
        faucet_mnemonic:
          type: string
        miner_coinbase_recipient:
          type: string
        miner_derivation_path:
          type: string
        miner_mnemonic:
          type: string
        namespace:
          type: string
        pox_2_activation:
          type: integer
          format: uint64
          minimum: 0.0
        project_manifest:
          $ref: '#/components/schemas/ProjectManifestConfig'
        stacks_node_first_attempt_time_ms:
          type: integer
          format: uint32
          minimum: 0.0
        stacks_node_subsequent_attempt_time_ms:
          type: integer
          format: uint32
          minimum: 0.0
        stacks_node_wait_time_for_microblocks:
          type: integer
          format: uint32
          minimum: 0.0
    StacksDevnetCreateResponse:
      type: object
      properties:
        thing:
          type: string
    AccountConfig:
      type: object
      required:
      - balance
      - mnemonic
      - name
      properties:
        balance:
          type: integer
          format: uint64
          minimum: 0.0
        derivation:
          type: string
        mnemonic:
          type: string
        name:
          type: string
    BtcTransferSpecificationFile:
      type: object
      required:
      - expected-sender
      - recipient
      - sats-amount
      - sats-per-byte
      properties:
        expected-sender:
          type: string
        recipient:
          type: string
        sats-amount:
          type: integer
          format: uint64
          minimum: 0.0
        sats-per-byte:
          type: integer
          format: uint64
          minimum: 0.0
    ClarityVersion:
      type: string
      enum:
      - Clarity1
      - Clarity2
    ContractCallSpecificationFile:
      type: object
      required:
      - contract-id
      - cost
      - expected-sender
      - method
      - parameters
      properties:
        anchor-block-only:
          type: boolean
        contract-id:
          type: string
        cost:
          type: integer
          format: uint64
          minimum: 0.0
        expected-sender:
          type: string
        method:
          type: string
        parameters:
          type: array
          items:
            type: string
    ContractConfig:
      type: object
      required:
      - clarity_version
      - epoch
      - name
      - source
      properties:
        clarity_version:
          $ref: '#/components/schemas/ClarityVersion'
        deployer:
          type: string
        epoch:
          $ref: '#/components/schemas/EpochSpec'
        name:
          type: string
        source:
          type: string
    ContractPublishSpecificationFile:
      type: object
      anyOf:
      - type: object
        required:
        - path
        properties:
          path:
            type: string
      - type: object
        required:
        - url
        properties:
          url:
            type: string
            format: uri
      required:
      - contract-name
      - cost
      - expected-sender
      properties:
        anchor-block-only:
          type: boolean
        clarity-version:
          type: integer
          format: uint8
          minimum: 0.0
        contract-name:
          type: string
        cost:
          type: integer
          format: uint64
          minimum: 0.0
        expected-sender:
          type: string
        path:
          type: string
        url:
          type: string
    DeploymentSpecificationFile:
      type: object
      required:
      - name
      - network
      properties:
        bitcoin-node:
          type: string
        genesis:
          anyOf:
          - $ref: '#/components/schemas/GenesisSpecificationFile'
          - type: 'null'
        id:
          type: integer
          format: uint32
          minimum: 0.0
        name:
          type: string
        network:
          type: string
        node:
          type: string
        plan:
          anyOf:
          - $ref: '#/components/schemas/TransactionPlanSpecificationFile'
          - type: 'null'
        stacks-node:
          type: string
    EmulatedContractCallSpecificationFile:
      type: object
      required:
      - contract-id
      - emulated-sender
      - method
      - parameters
      properties:
        contract-id:
          type: string
        emulated-sender:
          type: string
        method:
          type: string
        parameters:
          type: array
          items:
            type: string
    EmulatedContractPublishSpecificationFile:
      type: object
      anyOf:
      - type: object
        required:
        - path
        properties:
          path:
            type: string
      - type: object
        required:
        - url
        properties:
          url:
            type: string
            format: uri
      required:
      - contract-name
      - emulated-sender
      properties:
        clarity-version:
          type: integer
          format: uint8
          minimum: 0.0
        contract-name:
          type: string
        emulated-sender:
          type: string
        path:
          type: string
        url:
          type: string
    EpochSpec:
      type: string
      enum:
      - '2.0'
      - '2.05'
      - '2.1'
      - '2.2'
      - '2.3'
      - '2.4'
    GenesisSpecificationFile:
      type: object
      required:
      - contracts
      - wallets
      properties:
        contracts:
          type: array
          items:
            type: string
        wallets:
          type: array
          items:
            $ref: '#/components/schemas/WalletSpecificationFile'
    ProjectManifestConfig:
      type: object
      required:
      - name
      properties:
        authors:
          type: array
          items:
            type: string
        description:
          type: string
        name:
          type: string
        requirements:
          type: array
          items:
            type: string
    RequirementPublishSpecificationFile:
      type: object
      anyOf:
      - type: object
        required:
        - path
        properties:
          path:
            type: string
      - type: object
        required:
        - url
        properties:
          url:
            type: string
            format: uri
      required:
      - contract-id
      - cost
      - remap-sender
      properties:
        clarity-version:
          type: integer
          format: uint8
          minimum: 0.0
        contract-id:
          type: string
        cost:
          type: integer
          format: uint64
          minimum: 0.0
        path:
          type: string
        remap-principals:
          type: object
          additionalProperties:
            type: string
        remap-sender:
          type: string
        url:
          type: string
    StxTransferSpecificationFile:
      type: object
      required:
      - cost
      - expected-sender
      - mstx-amount
      - recipient
      properties:
        anchor-block-only:
          type: boolean
        cost:
          type: integer
          format: uint64
          minimum: 0.0
        expected-sender:
          type: string
        memo:
          type: string
        mstx-amount:
          type: integer
          format: uint64
          minimum: 0.0
        recipient:
          type: string
    TransactionPlanSpecificationFile:
      type: object
      required:
      - batches
      properties:
        batches:
          type: array
          items:
            $ref: '#/components/schemas/TransactionsBatchSpecificationFile'
    TransactionSpecificationFile:
      oneOf:
      - type: object
        required:
        - contract-call
        properties:
          contract-call:
            $ref: '#/components/schemas/ContractCallSpecificationFile'
        additionalProperties: false
      - type: object
        required:
        - contract-publish
        properties:
          contract-publish:
            $ref: '#/components/schemas/ContractPublishSpecificationFile'
        additionalProperties: false
      - type: object
        required:
        - emulated-contract-call
        properties:
          emulated-contract-call:
            $ref: '#/components/schemas/EmulatedContractCallSpecificationFile'
        additionalProperties: false
      - type: object
        required:
        - emulated-contract-publish
        properties:
          emulated-contract-publish:
            $ref: '#/components/schemas/EmulatedContractPublishSpecificationFile'
        additionalProperties: false
      - type: object
        required:
        - requirement-publish
        properties:
          requirement-publish:
            $ref: '#/components/schemas/RequirementPublishSpecificationFile'
        additionalProperties: false
      - type: object
        required:
        - btc-transfer
        properties:
          btc-transfer:
            $ref: '#/components/schemas/BtcTransferSpecificationFile'
        additionalProperties: false
      - type: object
        required:
        - stx-transfer
        properties:
          stx-transfer:
            $ref: '#/components/schemas/StxTransferSpecificationFile'
        additionalProperties: false
    TransactionsBatchSpecificationFile:
      type: object
      required:
      - id
      - transactions
      properties:
        epoch:
          anyOf:
          - $ref: '#/components/schemas/EpochSpec'
          - type: 'null'
        id:
          type: integer
          format: uint
          minimum: 0.0
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionSpecificationFile'
    WalletSpecificationFile:
      type: object
      required:
      - address
      - balance
      - name
      properties:
        address:
          type: string
        balance:
          type: string
        name:
          type: string