apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: stacks-blockchain
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: stacks-blockchain
    argocd.argoproj.io/instance: platform-user-resources.platform
  name: stacks-blockchain
  namespace: "{namespace}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: stacks-blockchain
      app.kubernetes.io/instance: "{user_id}"
      app.kubernetes.io/managed-by: stacks-devnet-api
      app.kubernetes.io/name: stacks-blockchain
  template:
    metadata:
      labels:
        app.kubernetes.io/component: stacks-blockchain
        app.kubernetes.io/instance: "{user_id}"
        app.kubernetes.io/managed-by: stacks-devnet-api
        app.kubernetes.io/name: stacks-blockchain
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
      containers:
        - command:
            - stacks-node
            - start
            - --config
            - /src/stacks-blockchain/Stacks.toml
          env:
            - name: STACKS_LOG_PP
              value: "1"
            - name: BLOCKSTACK_USE_TEST_GENESIS_CHAINSTATE
              value: "1"
          image: quay.io/hirosystems/stacks-node:devnet-3.0
          imagePullPolicy: IfNotPresent
          name: stacks-blockchain
          ports:
            - containerPort: 20444
              name: p2p
              protocol: TCP
            - containerPort: 20443
              name: rpc
              protocol: TCP
          volumeMounts:
            - mountPath: /src/stacks-blockchain
              name: stacks-blockchain
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 750Mi # todo: revisit allocation
            limits:
              memory: 750Mi # todo: revisit allocation
      volumes:
        - configMap:
            name: stacks-blockchain
          name: stacks-blockchain
