apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: stacks-signer-1
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: stacks-signer-1
    argocd.argoproj.io/instance: platform-user-resources.platform
  name: stacks-signer-1
  namespace: "{namespace}"
spec:
  replicas: 1
  serviceName: stacks-signer-1
  selector:
    matchLabels:
      app.kubernetes.io/component: stacks-signer-1
      app.kubernetes.io/instance: "{user_id}"
      app.kubernetes.io/managed-by: stacks-devnet-api
      app.kubernetes.io/name: stacks-signer-1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: stacks-signer-1
        app.kubernetes.io/instance: "{user_id}"
        app.kubernetes.io/managed-by: stacks-devnet-api
        app.kubernetes.io/name: stacks-signer-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
      containers:
        - name: stacks-signer-1
          command:
            - stacks-signer
            - run
            - --config=/src/stacks-signer-1/Signer.toml
          image: quay.io/hirosystems/stacks-signer:devnet-3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30001
              name: signer-event
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi # todo: revisit allocation
            limits:
              memory: 750Mi # todo: revisit allocation
          volumeMounts:
            - mountPath: /chainstate/
              name: signer-db
            - mountPath: /src/stacks-signer-1
              name: stacks-signer-1
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 750Mi # todo: revisit allocation
            limits:
              memory: 750Mi # todo: revisit allocation
      volumes:
        - configMap:
            name: stacks-signer-1
          name: stacks-signer-1
  volumeClaimTemplates:
    - metadata:
        name: signer-db
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: premium-rwo
        resources:
          requests:
            storage: 1Gi
