apiVersion: v1
kind: ServiceAccount
metadata:
  name: stacks-devnet-api-service-account
  namespace: devnet

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stacks-devnet-api-service-account
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "delete", "create"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stacks-devnet-api-service-account
subjects:
  - kind: ServiceAccount
    name: stacks-devnet-api-service-account
    namespace: devnet
roleRef:
  kind: ClusterRole
  name: stacks-devnet-api-service-account
  apiGroup: rbac.authorization.k8s.io

---  

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: stacks-devnet-api
  name: stacks-devnet-api
  namespace: devnet
spec:
  serviceAccountName: stacks-devnet-api-service-account
  containers:
  - command: ["stacks-devnet-api"]
    name: stacks-devnet-api-container
    image: hirosystems/stacks-devnet-api:ci
    imagePullPolicy: Never
    ports:
    - containerPort: 8477
      name: api
      protocol: TCP
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: stacks-devnet-api-conf

---
apiVersion: v1
kind: Service
metadata:
  name: stacks-devnet-api-service
  namespace: devnet
spec:
  ports:
  - name: api
    port: 8477
    protocol: TCP
    targetPort: 8477
    nodePort: 30000
  selector:
    name: stacks-devnet-api
  type: NodePort

