apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: bitcoind-chain-coordinator
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: bitcoind-chain-coordinator
  name: bitcoind-chain-coordinator
  namespace: "{namespace}"
spec:
  ports:
  - name: tcp-p2p
    port: 18444
    protocol: TCP
    targetPort: 18444
  - name: tcp-rpc
    port: 18443
    protocol: TCP
    targetPort: 18443
  - name: http-coordinator-in
    port: 20445
    protocol: TCP
    targetPort: 20445
  - name: http-coordinator-con
    port: 20446
    protocol: TCP
    targetPort: 20446
  selector:
    app.kubernetes.io/component: bitcoind-chain-coordinator
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: bitcoind-chain-coordinator
