apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: stacks-signer-1
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: stacks-signer-1
    argocd.argoproj.io/instance: platform-user-resources.platform
  name: stacks-signer-1
  namespace: "{namespace}"
spec:
  ports:
  - name: http-signer-event
    port: 30001
    protocol: TCP
    targetPort: 30001
  selector:
    app.kubernetes.io/component: stacks-signer-1
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: stacks-signer-1
