apiVersion: v1
kind: Service
metadata:
  name: stacks-blockchain-api
  namespace: "{namespace}"
spec:
  ports:
  - name: api
    port: 3999
    protocol: TCP
    targetPort: 3999
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: eventport
    port: 3700
    protocol: TCP
    targetPort: 3700
  selector:
    name: stacks-blockchain-api
