apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: stacks-blockchain-api
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: stacks-blockchain-api
  name: stacks-blockchain-api
  namespace: "{namespace}"
spec:
  ports:
  - name: api
    port: 3999
    protocol: TCP
    targetPort: 3999
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: eventport
    port: 3700
    protocol: TCP
    targetPort: 3700
  selector:
    app.kubernetes.io/component: stacks-blockchain-api
    app.kubernetes.io/instance: "{user_id}"
    app.kubernetes.io/managed-by: stacks-devnet-api
    app.kubernetes.io/name: stacks-blockchain-api
