apiVersion: v1
kind: Pod
metadata:
  labels:
    name: bitcoind-chain-coordinator
  name: bitcoind-chain-coordinator
  namespace: "{namespace}"
spec:
  containers:
  - command:
    - /usr/local/bin/bitcoind
    - -conf=/etc/bitcoin/bitcoin.conf
    - -nodebuglogfile
    - -pid=/run/bitcoind.pid
    image: quay.io/hirosystems/bitcoind:devnet-v3
    imagePullPolicy: IfNotPresent
    name: bitcoind
    ports:
    - containerPort: 18444
      name: p2p
      protocol: TCP
    - containerPort: 18443
      name: rpc
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/bitcoin
      name: bitcoind
      readOnly: true
  - command:
    - ./stacks-network
    - --namespace=$(NAMESPACE)
    - --manifest-path=/etc/stacks-network/project/Clarinet.toml
    - --network-manifest-path=/etc/stacks-network/project/settings/Devnet.toml
    - --deployment-plan-path=/etc/stacks-network/project/deployments/default.devnet-plan.yaml
    - --project-root-path=/etc/stacks-network/project/
    env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
    image: hirosystems/stacks-network-orchestrator@sha256:1a1f60688759bc742bd1b64384eedba38faed46e0067cb3c121914004fe1df0a
    imagePullPolicy: IfNotPresent
    name: chain-coordinator
    ports:
    - containerPort: 20445
      name: coordinator-in
      protocol: TCP
    - containerPort: 20446
      name: coordinator-con
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/stacks-network/project
      name: project-manifest
    - mountPath: /etc/stacks-network/project/settings
      name: devnet
    - mountPath: /etc/stacks-network/project/deployments
      name: deployment-plan
    - mountPath: /etc/stacks-network/project/contracts
      name: project-dir
  volumes:
  - configMap:
      name: bitcoind
    name: bitcoind
  - configMap:
      name: project-manifest
    name: project-manifest
  - configMap:
      name: devnet
    name: devnet
  - configMap:
      name: deployment-plan
    name: deployment-plan
  - configMap:
      name: project-dir
    name: project-dir
