apiVersion: v1
kind: Pod
metadata:
  labels:
    name: stacks-blockchain-api
  name: stacks-blockchain-api
  namespace: "{namespace}"
spec:
  containers:
  - name: stack-blockchains-api
    envFrom:
      - configMapRef:
          name: stacks-blockchain-api
          optional: false
    image: hirosystems/stacks-blockchain-api
    imagePullPolicy: Always
    ports:
    - containerPort: 3999
      name: api
      protocol: TCP
    - containerPort: 3700
      name: eventport
      protocol: TCP
  - name: postgres
    envFrom:
      - configMapRef:
          name: stacks-blockchain-api-pg
          optional: false
    image: postgres:14
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5432
      name: postgres
      protocol: TCP
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: stacks-blockchain-api-pg
  volumes:
  - name: stacks-blockchain-api-pg
    persistentVolumeClaim:
      claimName: stacks-blockchain-api-pg
