apiVersion: v1
kind: Pod
metadata:
  labels:
    name: stacks-blockchain
  name: stacks-blockchain
  namespace: "{namespace}"
spec:
  containers:
  - command:
    - stacks-node
    - start
    - --config=/src/stacks-blockchain/Stacks.toml
    env:
    - name: STACKS_LOG_PP
      value: "1"
    - name: BLOCKSTACK_USE_TEST_GENESIS_CHAINSTATE
      value: "1"
    - name: STACKS_LOG_DEBUG
      value: "0"
    image: quay.io/hirosystems/stacks-node:devnet-v3
    imagePullPolicy: IfNotPresent
    name: stacks-blockchain
    ports:
    - containerPort: 20444
      name: p2p
      protocol: TCP
    - containerPort: 20443
      name: rpc
      protocol: TCP
    volumeMounts:
    - mountPath: /src/stacks-blockchain
      name: stacks-blockchain
      readOnly: true
  volumes:
  - configMap:
      name: stacks-blockchain
    name: stacks-blockchain