apiVersion: v1
kind: Pod
metadata:
  labels:
    name: bitcoind
    service: bitcoind-chain-coordinator
  name: bitcoind
  namespace: "{namespace}"
spec:
  containers:
  - command:
    - /usr/local/bin/bitcoind
    - -conf=/etc/bitcoin/bitcoin.conf
    - -nodebuglogfile
    - -pid=/run/bitcoind.pid
    image: quay.io/hirosystems/bitcoind:devnet-v3
    imagePullPolicy: IfNotPresent
    name: bitcoind-container
    ports:
    - containerPort: 18444
      name: p2p
      protocol: TCP
    - containerPort: 18443
      name: rpc
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/bitcoin
      name: bitcoind-conf-volume
      readOnly: true
  volumes:
  - configMap:
      name: bitcoind-conf
    name: bitcoind-conf-volume