apiVersion: v1
kind: Pod
metadata:
  labels:
    name: stacks-node
  name: stacks-node
  namespace: "{namespace}"
spec:
  containers:
  - command:
    - stacks-node
    - start
    - --config=/src/stacks-node/Stacks.toml
    env:
    - name: STACKS_LOG_PP
      value: "1"
    - name: BLOCKSTACK_USE_TEST_GENESIS_CHAINSTATE
      value: "1"
    - name: STACKS_LOG_DEBUG
      value: "0"
    image: quay.io/hirosystems/stacks-node:devnet-v3
    imagePullPolicy: IfNotPresent
    name: stacks-node-container
    ports:
    - containerPort: 20444
      name: p2p
      protocol: TCP
    - containerPort: 20443
      name: rpc
      protocol: TCP
    volumeMounts:
    - mountPath: /src/stacks-node
      name: stacks-node-conf-volume
      readOnly: true
    - mountPath: /devnet
      name: stacks-node-data-volume
      readOnly: false
  volumes:
  - name: stacks-node-conf-volume
    configMap:
      name: stacks-node-conf
  - name: stacks-node-data-volume
    persistentVolumeClaim:
      claimName: stacks-node-pvc