apiVersion: v1
kind: ServiceAccount
metadata:
  name: stacks-devnet-api
  namespace: devnet

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stacks-devnet-api
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services", "configmaps"]
    verbs: ["get", "delete", "create", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "delete", "create", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stacks-devnet-api
subjects:
  - kind: ServiceAccount
    name: stacks-devnet-api
    namespace: devnet
roleRef:
  kind: ClusterRole
  name: stacks-devnet-api
  apiGroup: rbac.authorization.k8s.io

---  

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: stacks-devnet-api
  name: stacks-devnet-api
  namespace: devnet
spec:
  serviceAccountName: stacks-devnet-api
  containers:
  - command: ["stacks-devnet-api"]
    name: stacks-devnet-api
    image: stacks-devnet-api
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8478
      name: api
      protocol: TCP
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: stacks-devnet-api

---
apiVersion: v1
kind: Service
metadata:
  name: stacks-devnet-api
  namespace: devnet
spec:
  ports:
  - name: api
    port: 8477
    protocol: TCP
    targetPort: 8478
    nodePort: 30000
  selector:
    name: stacks-devnet-api
  type: NodePort

